CREATE DATABASE SoftUni

USE SoftUni

CREATE TABLE Towns(
Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Addresses(
Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
AddressText NVARCHAR(30) NOT NULL,
TownId INT NOT NULL
)

ALTER TABLE Addresses
ADD CONSTRAINT FK_TownId
FOREIGN KEY (TownId) REFERENCES Towns(Id)

CREATE TABLE Departments(
Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Employees(
Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
FirstName NVARCHAR(30) NOT NULL,
MiddleName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
JobTitle NVARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATE NOT NULL,
Salary DECIMAL(15, 2) NOT NULL,
AddressId INT NOT NULL
)

ALTER TABLE Employees
ADD CONSTRAINT FK_DepartmentId
FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)

ALTER TABLE Employees
ADD CONSTRAINT FK_AddressId
FOREIGN KEY (AddressId) REFERENCES Addresses(Id)